import Head from 'next/head'
import Image from 'next/image'
import CarouselN from '../components/Carousel/Carousel'
import Footer from '../components/Footer/Footer'
import Header from '../components/Header/Header'
import Services from '../components/Services/Services'
import styles from '../styles/Home.module.css'
import '../firebase.init'
import Courses from '../components/Course/Courses'
import HomeOnlyShowSomeCourse from '../components/Course/HomeOnlyShowSomeCourse'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ED-Tech Ltd.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <CarouselN />

      <main>
        <HomeOnlyShowSomeCourse />
        <Services />
      </main>

      <Footer />
    </div>
  )
}


